### ISSUE TITLE
"parameters" vs "input_data" in generate function signature

### ISSUE THREAD

**Issue by VTimofeenko** [cloudblue/connect-report-python-boilerplate#14]
The current version of the project [has](https://github.com/cloudblue/connect-report-python-boilerplate/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.package_slug%7D%7D/%7B%7Bcookiecutter.initial_report_slug%7D%7D/entrypoint.py#L8)

```python
def generate(
    client=None,
    input_data=None,
    progress_callback=None,
    renderer_type='{{ cookiecutter.initial_report_renderer }}',
    extra_context_callback=None,
):
...
```

Whereas `reports.json` and examples in [connect-reports repo](https://github.com/cloudblue/connect-reports) have "parameters".

Can you please clarify whether that argument should be "input_data" or "parameters"?

**Comment by marcserrat** [comment]
HI VTimofeenko

A pleasure to answer your question, thanks for rising it. Currently, reports have 2 specifications, in other words, v1 and v2.
Both specifications allow running reports but with slight differences in terms of power: v1 can only have XLSX as renderer while v2 can have XLSX, JSON, PDF, and others and a single report can even have more than one at the same time.

Please note that the difference between both specifications is the number of arguments passed to generate function, but such arguments even those that are defined as kwargs, are handled as positional ones in order to ensure backward compatibility between both specifications.

**Comment by VTimofeenko** [comment]
Thanks, @marcserrat ! From working with Connect reports and running them locally vs in Connect I gathered some syntactic differences between `report_spec = 1` and `report_spec = 2`. Would it be possible to clarify those differences in the [doc](https://connect.cloudblue.com/community/sdk/connect-reports-sdk/)?
